### PR TITLE
v0.2.0

### PR DESCRIPTION
**Pull request by hauntedhost**
Thanks for Pandex! I realize this is a pretty big PR so no offense taken if you'd rather not merge this. We're planning to use this fork at [StatMuse](https://github.com/statmuse) though so I figured I'd see if you're interested in these changes. Let me know if you have any questions or feedback. 

- bump version to 0.2.0 (functionality was mostly added in a backwards-compatible manner, sans removal of from/to defaults which will loudly break callers relying on this vs. silently doing something unexpected. via semver `0.y.z` "is for initial development. Anything may change at any time. The public API should not be considered stable.")
- move most tests to pandex_test.exs
- cleanup and fix all tests for pandoc 2.5
- add test that pandoc version >= 2.5
- add note re: deprecated github_markdown format
- add gfm format
- remove potentially confusing from/to defaults
- add guards to convert_string/file
- convert_string/file passes options to System.cmd
- generated helper fns also accept and pass options
- convert_string/file returns :error tuple on failure
- simplify random_filename logic

### CODE REVIEW

**Comment by hauntedhost** [comment]
@FilterKaapi Also thought I'd mention, I'd be happy to help (or even takeover) as maintainer of this library if that's appealing to you. Thanks again.

**Comment by FilterKaapi** [comment]
Hi @somlor Agree with you. I joined AWS in a BizDev role (change of career for me from tech) 2.5 years ago. And honestly I haven't had the time to maintain any of my projects. I am adding you as a collaborator so that the project is actively managed. Thanks!

**Comment by hauntedhost** [comment]
Hey, congrats on new role. Makes sense. And thanks for adding me as collaborator! I think I'll add [Travis CI](https://travis-ci.org) testing to this PR before merging. Will be after the holidays.

Meanwhile, would you mind adding me as an owner of the hex.pm package as well? That way I can also publish new versions there:
```bash
mix hex.owner add pandex seanomlor
```
via: https://hexdocs.pm/hex/Mix.Tasks.Hex.Owner.html

**Comment by jalcine** [comment]
Bumping this PR again (cc: @FilterKaapi  @somlor). I'd love to use this!

**Comment by hauntedhost** [comment]
@FilterKaapi let me know if you have any questions or concerns re: adding me as an owner of the hex.pm package. Would love to merge this PR and publish a new version that people can start using.

**Comment by krystofbe** [comment]
@FilterKaapi 
Would love to see this getting merged. After merging we could add support for more formats (I'm using it for `docx` and `pdf` generation on my own fork)

**Comment by FilterKaapi** [comment]
@seanomlor added you as the owner on hex as well. Pls confirm that it reflects. Apologies for the delays.

**Comment by hauntedhost** [comment]
Thanks @FilterKaapi -- Merged and published `0.2.0` https://hex.pm/packages/pandex

Will tackle Travis integration as separate issue: https://github.com/FilterKaapi/pandex/issues/5

**Pull request merged**
